//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Azure.ServiceBus.KeyVault {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Resources() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Azure.ServiceBus.KeyVault.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///    Looks up a localized string similar to An exception occured while trying to decrypt a message.
        /// </summary>
        public static string AfterMessageReceiveException
        {
            get
            {
                return ResourceManager.GetString("AfterMessageReceiveException", resourceCulture);
            }
        }

        /// <summary>
        ///    Looks up a localized string similar to Could not acquire Azure AD token for KeyVault access. KeyVault: &apos;{0}&apos;.
        /// </summary>
        public static string AzureAdTokenAcquisitionFailure {
            get {
                return ResourceManager.GetString("AzureAdTokenAcquisitionFailure", resourceCulture);
            }
        }

        /// <summary>
        ///    Looks up a localized string similar to An exception occured while trying to encrypt a message.
        /// </summary>
        public static string BeforeMessageSendException
        {
            get
            {
                return ResourceManager.GetString("BeforeMessageSendException", resourceCulture);
            }
        }

        /// <summary>
        ///    Looks up a localized string similar to Could not acquire KeyVault token. Token name: &apos;{0}&apos; KeyVault: &apos;{1}&apos;.
        /// </summary>
        public static string KeyVaultKeyAcquisitionFailure {
            get {
                return ResourceManager.GetString("KeyVaultKeyAcquisitionFailure", resourceCulture);
            }
        }
    }
}
